### ISSUE TITLE
Question: Build Items are not vanilla compatible?

### ISSUE THREAD

**Issue by himpich** [JereKuusela/valheim-structure_tweaks#5]
Are the build Items vanilla compatible? I am asking because I would like to have an item non-colliding (so you fall through them) but it should work on vanilla clients - it is not possible right? and I should go back to using rugs?

Thanks for clarifying,
Stefan

**Comment by JereKuusela** [comment]
Nothing from this mod is vanilla compatible. That's the purpose of this mod.

**Comment by himpich** [comment]
Thanks for clarifying that.
